import { test, expect } from '../fixtures/test-fixtures';
import { users, customer, products } from '../test-data/data';

test.describe('@functional core journeys', () => {
  test('TC-001 valid login shows inventory @smoke', async ({ login, inventory }) => { await login.goto(); await login.login(users.standard.username, users.standard.password); await inventory.expectLoaded(); });
  test('TC-002 inventory cards show names and prices', async ({ login, inventory }) => { await login.goto(); await login.login(users.standard.username, users.standard.password); await inventory.expectLoaded(); for (const p of products) { await expect(inventory.item(p.name)).toBeVisible(); await expect(inventory.item(p.name).getByTestId('inventory-item-price')).toHaveText(p.price); } });
  test('TC-003 add one product', async ({ login, inventory }) => { await login.goto(); await login.login(users.standard.username, users.standard.password); await inventory.add(products[0].name); await inventory.expectCartCount(1); });
  test('TC-004 add multiple products @smoke', async ({ login, inventory }) => { await login.goto(); await login.login(users.standard.username, users.standard.password); for (const p of products) await inventory.add(p.name); await inventory.expectCartCount(2); });
  test('TC-005 cart has correct product quantity and price', async ({ login, inventory, cart }) => { await login.goto(); await login.login(users.standard.username, users.standard.password); for (const p of products) await inventory.add(p.name); await inventory.openCart(); for (const p of products) await cart.expectItem(p.name, p.price); });
  test('TC-006 remove product from inventory', async ({ login, inventory }) => { await login.goto(); await login.login(users.standard.username, users.standard.password); await inventory.add(products[0].name); await inventory.remove(products[0].name); await inventory.expectCartCount(0); });
  test('TC-007 remove product from cart', async ({ login, inventory, cart }) => { await login.goto(); await login.login(users.standard.username, users.standard.password); await inventory.add(products[0].name); await inventory.openCart(); await cart.remove(products[0].name); await expect(cart.items).toHaveCount(0); });
  test('TC-008 continue shopping returns to inventory', async ({ login, inventory, page }) => { await login.goto(); await login.login(users.standard.username, users.standard.password); await inventory.openCart(); await page.getByTestId('continue-shopping').click(); await inventory.expectLoaded(); });
  test('TC-009 valid checkout reaches overview', async ({ login, inventory, cart, checkout, page }) => { await login.goto(); await login.login(users.standard.username, users.standard.password); await inventory.add(products[0].name); await inventory.openCart(); await cart.checkout(); await checkout.fill(customer); await checkout.continue(); await expect(page).toHaveURL(/checkout-step-two\.html/); });
  test('TC-010 order subtotal is correct', async ({ login, inventory, cart, checkout, page }) => { await login.goto(); await login.login(users.standard.username, users.standard.password); for (const p of products) await inventory.add(p.name); await inventory.openCart(); await cart.checkout(); await checkout.fill(customer); await checkout.continue(); await expect(page.getByTestId('summary-subtotal-label')).toContainText('$39.98'); });
  test('TC-011 complete order confirmation @smoke', async ({ login, inventory, cart, checkout }) => { await login.goto(); await login.login(users.standard.username, users.standard.password); await inventory.add(products[0].name); await inventory.openCart(); await cart.checkout(); await checkout.fill(customer); await checkout.continue(); await checkout.finish(); await checkout.expectConfirmation(); });
  test('TC-012 sort products low to high', async ({ login, inventory, page }) => { await login.goto(); await login.login(users.standard.username, users.standard.password); await page.getByTestId('product-sort-container').selectOption('lohi'); const values = await inventory.items.getByTestId('inventory-item-price').allTextContents(); const prices = values.map(v => Number(v.replace('$',''))); expect(prices).toEqual([...prices].sort((a,b)=>a-b)); });
});
